# PARAMETERS TO CONTROL THE BEHAVIOR OF THE GAME ENGINE
# DO NOT REMOVE OR RENAME THIS FILE
PLAYER_1_NAME = 'GTOWizard AI'
PLAYER_1_PATH = './csrc/main_bot'
# NO TRAILING SLASHES ARE ALLOWED IN PATHS
PLAYER_2_NAME = 'GTOWizard AI'
PLAYER_2_PATH = './csrc/main_bot'
# GAME PROGRESS IS RECORDED HERE
GAME_LOG_FILENAME = 'gamelog'
# PLAYER_LOG_SIZE_LIMIT IS IN BYTES
PLAYER_LOG_SIZE_LIMIT = 524288
# STARTING_GAME_CLOCK AND TIMEOUTS ARE IN SECONDS
ENFORCE_GAME_CLOCK = True
STARTING_GAME_CLOCK = 30.
BUILD_TIMEOUT = 120.
CONNECT_TIMEOUT = 10.
# THE GAME VARIANT FIXES THE PARAMETERS BELOW
# CHANGE ONLY FOR TRAINING OR EXPERIMENTATION
NUM_ROUNDS = 1000
STARTING_STACK = 400
BIG_BLIND = 2
SMALL_BLIND = 1
